### ISSUE TITLE
프로젝트 라이브러리 선택

### ISSUE THREAD

**Issue by boseungk** [Step3-kakao-tech-campus/Team13_BE#1]
##  Description
- 라이브러리 선택

## TO DO
- [x] 프로젝트 라이브러리 선택

## Etc
- Java 17
- Gradle 8.2.1
- Spring Boot 3.1.4
- JPA 3.1.4
- QueryDSL 5.0.0
- Spring Security 6.1.4
- MySQL 8.0.33
- Docker
- Redis

**Comment by November8th** [comment]
금일 자정까지 완료해주시면 좋을 것 같습니다
